language: php

install: echo "skip install"

branches:
  only:
  - master

before_install:
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_30d566ffdf42_key -iv $encrypted_30d566ffdf42_iv
  - in deploy_key.enc -out deploy_key -d

script:
  - ls -al style.css

after_success: bash ./.bin/deploy.sh

env:
  global:
  - GH_REF: github.com/featherplain/asknode.git
  - secure: "Ne0j+T6CZrKRWG/xGP80d2IukmdUEF+PXoDZZiYZykzpny6Zql6cVRHALZ7dDak0rV6juLE2lNysF00d0KdLSwm2rOt7XQVVb8SxtAt2HGnq9nTppwOLxDp8N0FHh9cVdiFie26btci13BeN+ZHfB7+QbUqN14cokdSsa+5WoDN1Xde2xdjt6Rw645hSqKcQBKPQOKiWxnLxL8v4a8CcQ1BE0TUYfne8fhjaqcCgECDdSMNuiXJOHYAXuS05GHRwY0zInMu2OvN5iQ9VfAjvScHfHI9DhW2dHhdAv3HzmMIz8K6IHGWj6senstJxi/PF/Uom/hqbXF3mDq9eRY+bDGH9zG3E+zHiALGOaQt/KTBXJVDpS7J0Sd8k2Pxma6bwLJ8ibzRo/bKOzToqcTjnjFd+2pZxwyLW2tPdSNOa60LYfJsjDEWCESRz3Z9rIrZAEwXzSEI0AIB4Aqud1A2ID4V0mH2fh+cytdiz6cMAxI6CfP6ZO5QNyEEPR5BUkJyjd8Qba7XfsKcn0R33HtQt8A94DBEO+LdzyAHs+h40xlzESZwV0MGXesgyIkPjWiaSZV26TYgBRjAfuXxSEH0nKo7f7+BmhMXEq14K+Vo0Li1+ibZplIebJVsL8xMqYEqxTLGa6fSc1apLxWMqjyd3I1ucI0/i9LMAdqPTGCnMvj8="
  - secure: "mu21Yj2xCA5Qtmd6hfMyYDj4gxF25wXdbMjQQkjqum2yFSHHM/5VEvHCzTUrZBkUOnyfoe3YX/EH8m5j7t3UmmJGXwdQvyZMLxeMRCGPJTEyAesy2Xg/iPyPZ3bv6fT0sqFeagVsUGArOVyXpcraL+gbFlain25PVJ9H8h1qMejsE2sGXyH/1eN6/B/7Ciy7O7UXvoCS2Ny4duvBCDBFcxW/Es82vK6264PLevcNkQjqKFXgChuQ2QOUI343ubTRzPHbV3ogxzcD5UjxNFT/KXkVNh5lMM4srrdr8faTw85vyW64RA/4V3Nxl+bVwQJsyb4ieypgf43G5L/XcCU7pfeHZz7Wn+AhmKPFUcOndBWmdDY1G/NsMtUjBi9Z/hEzVJJSIvqvyglPFnaW577g2HvCmmVfCL/Y+9fTRpygryVe4dDqKoQTXz+m5BsvbwfSP/O1PulBbtQxeysUs0/HTam77PQyBFmfEH2glpPdh+zcmOh/3sTQjhqs/79h+7jzGWRHkyIkPjrrVtzRgS1OMDgfnJtsbXpudTTIubMm0R+DE+x7tWA5p9sAqt2QZWrQjpKMpiHZnaHMgBBW6GAOyXNkim09NzV0oKt+AAQzTqrjTn/Ef8lU+wbxxFO8B1OqHX7NSSjBWhMxlclwJiNk5goRahj7O0zTKBu8NBNVLjA="
  - secure: "Ar8+oIS0HwzD/kOTeOHhxgjokzqZAhzRhtOVNHMO8k5pcpsJ+YEwC56OkuiEHmvI40HDSLUlONswtRJgg3+RX6yHNGO7Ica0KyZgOKU1lyj1N+dXo1nS4MdJJvzUDWxMcjnVkyk3BXG1dlahJCmak6OG4aZOw9WGtim4KGori6hQvKgzzOXIfdkpJ/h4MaWWo2JAjjqItB0Q1aDDlSnPHxW/L4hmlYvVkJI6mJCYRfr1lpyxjVrnaLBqLaaomOMTEA6D12OtpVjeIogKSZr9jnShB12y9K9jeAjvqe/g7Lr8ig9TkuZIJq/T0n1dn/efKGCgzZ897zDfpuZyJprC4iX/9uztm46GELDE1UCyvYtxyPfPA53krdA44+WeB4NmZWvdPiIwuO2OonfoEC/ORW1DQEq+O4VmFkbNyulH0nwwukQ7GwPWMJx3PxcAK+6W4MLrRY8bqXMg5+FXz/DDKw/bTpHjPv+XgVUjJs5d99/uFU9YXgEAEOv+9ZEUs8/62JAGqSKZfB0Bp3MC8jdH2yzCU9AAQE3/cE4FunynzpsqljmI8ynGYQeWDdDN7mPBKx/wE9CSds65UQNnwjtYce5WB19ni9QsgkpJWdbO+eDvhqtAdTm2CObSH9KgPdfdt4iOkX6O2T4Rq1PmJCnnCl5HC8y39cwr/n86svfE5Io="
  - secure: "DJEibchIAQ7FKgfgEmDBUR0mk4OPU8Kw/Rr2JSfPP2jfoWUtKOqfYR57pUSMu1Y3WW+AIuZTtInqZaaxS0CoWEeAcncnDSv/TDQcO+1mm0d93/b8poWDP0DfnBg7ZVcy9rJhk7lrNQkEOYFS6AFYFuK4XITtVh8ZtIrrOEZXEjsT4zhhiaFH2RHKwjnmMjW9YQJDb+TJtwTEXaFz/CtbVP3uNonW5c0yl6wbnh/IRNpvhRySbQ5UWBX3kjelJXmRM9agxfmLd1Dm7Xuel266hJsJwgTuUaOpu4JX/RU3vNchHGCrisyRlBkl6fzuE7PDLjUMBVx1w2PugGRdYoRodf90FQBfnJl6ikDkCpKDgKDgqi/VwjrRe/f0lcpg8t2D/xFSLFE2mHbIKwJzc00YaThypqi1mMhdmBNJGaVgEBZBb11iL4WaB0WFmMzL6MnWp5Zhc70aozlNz/INyAn7yEVyMCEEMxAMIkqjITsj0dBwwVFsvlir/l3KzPyApPRtg1XnuMtA9LVDjI/s036JeTt2f7HmKXjphAJ7VuWPDDzMgsql9ZZ6Kti7qBNok7kRRWvYNyCcqhZuZnXBwqWAxx/Lo8ZnibUATVKXpMeLkHgoUf5FTEFkW5dnXH5fMpzDTT+vbQLe1floMddAUEuY8VUpoUwFmTCRtWGPDiNoGpY="
  -
